package Get_API_Testing_BDD_Approach;

public class Git_Post_response {

	public static String post_Resonse() {

		String res =  "{\n" + "    \"id\": 296474047,\n"
				+ "    \"node_id\": \"MDEwOlJlcG9zaXRvcnkyOTY0NzQwNDc=\",\n"
				+ "    \"name\": \"created_By_restAssured\",\n"
				+ "    \"full_name\": \"hal0998/created_By_restAssured\",\n" + "    \"private\": false,\n"
				+ "    \"owner\": {\n" + "        \"login\": \"hal0998\",\n" + "        \"id\": 43451977,\n"
				+ "        \"node_id\": \"MDQ6VXNlcjQzNDUxOTc3\",\n"
				+ "        \"avatar_url\": \"https://avatars2.githubusercontent.com/u/43451977?v=4\",\n"
				+ "        \"gravatar_id\": \"\",\n" + "        \"url\": \"https://api.github.com/users/hal0998\",\n"
				+ "        \"html_url\": \"https://github.com/hal0998\",\n"
				+ "        \"followers_url\": \"https://api.github.com/users/hal0998/followers\",\n"
				+ "        \"following_url\": \"https://api.github.com/users/hal0998/following{/other_user}\",\n"
				+ "        \"gists_url\": \"https://api.github.com/users/hal0998/gists{/gist_id}\",\n"
				+ "        \"starred_url\": \"https://api.github.com/users/hal0998/starred{/owner}{/repo}\",\n"
				+ "        \"subscriptions_url\": \"https://api.github.com/users/hal0998/subscriptions\",\n"
				+ "        \"organizations_url\": \"https://api.github.com/users/hal0998/orgs\",\n"
				+ "        \"repos_url\": \"https://api.github.com/users/hal0998/repos\",\n"
				+ "        \"events_url\": \"https://api.github.com/users/hal0998/events{/privacy}\",\n"
				+ "        \"received_events_url\": \"https://api.github.com/users/hal0998/received_events\",\n"
				+ "        \"type\": \"User\",\n" + "        \"site_admin\": false\n" + "    },\n"
				+ "    \"html_url\": \"https://github.com/hal0998/created_By_restAssured\",\n"
				+ "    \"description\": null,\n" + "    \"fork\": false,\n"
				+ "    \"url\": \"https://api.github.com/repos/hal0998/created_By_restAssured\",\n"
				+ "    \"forks_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/forks\",\n"
				+ "    \"keys_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/keys{/key_id}\",\n"
				+ "    \"collaborators_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/collaborators{/collaborator}\",\n"
				+ "    \"teams_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/teams\",\n"
				+ "    \"hooks_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/hooks\",\n"
				+ "    \"issue_events_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/issues/events{/number}\",\n"
				+ "    \"events_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/events\",\n"
				+ "    \"assignees_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/assignees{/user}\",\n"
				+ "    \"branches_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/branches{/branch}\",\n"
				+ "    \"tags_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/tags\",\n"
				+ "    \"blobs_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/git/blobs{/sha}\",\n"
				+ "    \"git_tags_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/git/tags{/sha}\",\n"
				+ "    \"git_refs_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/git/refs{/sha}\",\n"
				+ "    \"trees_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/git/trees{/sha}\",\n"
				+ "    \"statuses_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/statuses/{sha}\",\n"
				+ "    \"languages_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/languages\",\n"
				+ "    \"stargazers_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/stargazers\",\n"
				+ "    \"contributors_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/contributors\",\n"
				+ "    \"subscribers_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/subscribers\",\n"
				+ "    \"subscription_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/subscription\",\n"
				+ "    \"commits_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/commits{/sha}\",\n"
				+ "    \"git_commits_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/git/commits{/sha}\",\n"
				+ "    \"comments_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/comments{/number}\",\n"
				+ "    \"issue_comment_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/issues/comments{/number}\",\n"
				+ "    \"contents_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/contents/{+path}\",\n"
				+ "    \"compare_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/compare/{base}...{head}\",\n"
				+ "    \"merges_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/merges\",\n"
				+ "    \"archive_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/{archive_format}{/ref}\",\n"
				+ "    \"downloads_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/downloads\",\n"
				+ "    \"issues_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/issues{/number}\",\n"
				+ "    \"pulls_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/pulls{/number}\",\n"
				+ "    \"milestones_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/milestones{/number}\",\n"
				+ "    \"notifications_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/notifications{?since,all,participating}\",\n"
				+ "    \"labels_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/labels{/name}\",\n"
				+ "    \"releases_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/releases{/id}\",\n"
				+ "    \"deployments_url\": \"https://api.github.com/repos/hal0998/created_By_restAssured/deployments\",\n"
				+ "    \"created_at\": \"2020-09-18T00:37:54Z\",\n" + "    \"updated_at\": \"2020-09-18T00:37:54Z\",\n"
				+ "    \"pushed_at\": \"2020-09-18T00:37:55Z\",\n"
				+ "    \"git_url\": \"git://github.com/hal0998/created_By_restAssured.git\",\n"
				+ "    \"ssh_url\": \"git@github.com:hal0998/created_By_restAssured.git\",\n"
				+ "    \"clone_url\": \"https://github.com/hal0998/created_By_restAssured.git\",\n"
				+ "    \"svn_url\": \"https://github.com/hal0998/created_By_restAssured\",\n"
				+ "    \"homepage\": null,\n" + "    \"size\": 0,\n" + "    \"stargazers_count\": 0,\n"
				+ "    \"watchers_count\": 0,\n" + "    \"language\": null,\n" + "    \"has_issues\": true,\n"
				+ "    \"has_projects\": true,\n" + "    \"has_downloads\": true,\n" + "    \"has_wiki\": true,\n"
				+ "    \"has_pages\": false,\n" + "    \"forks_count\": 0,\n" + "    \"mirror_url\": null,\n"
				+ "    \"archived\": false,\n" + "    \"disabled\": false,\n" + "    \"open_issues_count\": 0,\n"
				+ "    \"license\": null,\n" + "    \"forks\": 0,\n" + "    \"open_issues\": 0,\n"
				+ "    \"watchers\": 0,\n" + "    \"default_branch\": \"master\",\n" + "    \"permissions\": {\n"
				+ "        \"admin\": true,\n" + "        \"push\": true,\n" + "        \"pull\": true\n" + "    },\n"
				+ "    \"allow_squash_merge\": true,\n" + "    \"allow_merge_commit\": true,\n"
				+ "    \"allow_rebase_merge\": true,\n" + "    \"delete_branch_on_merge\": false,\n"
				+ "    \"network_count\": 0,\n" + "    \"subscribers_count\": 1\n" + "}\n" + "";
		return res;
	}

}
